trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: GoTool@0
    inputs:
      version: '1.18.2'
  - task: Go@0
    inputs:
      command: 'test'
      arguments: '-v'
      workingDirectory: '$(System.DefaultWorkingDirectory)'